apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}"
data:
  image: "{{ .Values.image }}"
  version: "{{ .Values.version }}"
  deployment_id: "{{ .Values.deployment }}"
  bucket: "{{ .Values.bucket }}"
  NR_APP_NAME: "{{ .Values.name }}-{{ .Values.namespace }}"