apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
    version: "{{ .Values.version }}"
spec:
  replicas: {{ int .Values.replicas }} 
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      imagePullSecrets:
      - name: "{{.Values.name}}-dockercfg"
      containers:
        - name: "{{ .Values.name }}"
          image: "{{ .Values.image }}"
          args: ["-text=image: $(image) \nversion: $(version) \ndeployment: $(deployment_id) \npod: $(pod_name) "]
          env:
            - name: pod_name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: "{{.Values.name}}"
          ports:
            - name: http
              containerPort: 5678
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
