name: <+stage.variables.name>
deployment: <+pipeline.executionId>
replicas: 2

image: <+artifact.image>
version: <+artifact.tag>
dockercfg: <+artifact.imagePullSecret>
bucket: <+pipeline.stages.Canary_Deploy.spec.execution.steps.Provision_Infrastructure.steps.Terraform_Apply.output.bucket>

namespace: <+infra.namespace>

nrLicense: <+secrets.getValue("newreliclicense")>
