name: <+stage.variables.name>
deployment: <+pipeline.executionId>
replicas: 2

image: <+artifact.image>
version: <+artifact.tag>
dockercfg: <+artifact.imagePullSecret>
bucket: <+<+infrastructureDefinition.provisioner.steps.Terraform_Apply.output.bucket>

namespace: <+infra.namespace>
